name: Test Package

on:
  workflow_dispatch:       # запуск вручную

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8","3.9","3.10","3.11","3.12","3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install FFmpeg (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install FFmpeg (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install ffmpeg
    
    - name: Install FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install ffmpeg -y

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build hatchling pytest soundfile

    - name: Build package
      run: python -m build --wheel --outdir dist

    - name: Install package
      run: |
        import glob, subprocess, sys
        whl = glob.glob("dist/*.whl")[0]
        subprocess.check_call([sys.executable, "-m", "pip", "install", whl])
      shell: python

    - name: Install torchcodec
      run: |
        # Только ПОСЛЕ установки вашего пакета
        pip install torchcodec

    - name: Run tests
      run: pytest tests